# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .CardanoAddressParametersType import CardanoAddressParametersType

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class CardanoTxOutputType(p.MessageType):

    def __init__(
        self,
        *,
        amount: int,
        address: str = None,
        address_parameters: CardanoAddressParametersType = None,
    ) -> None:
        self.amount = amount
        self.address = address
        self.address_parameters = address_parameters

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('address', p.UnicodeType, None),
            3: ('amount', p.UVarintType, p.FLAG_REQUIRED),
            4: ('address_parameters', CardanoAddressParametersType, None),
        }
